### ISSUE TITLE
how it works in monaco-editor!

### ISSUE THREAD

**Issue by yuangegena** [srares13/vscode-position-tracking#1]
I want to use it in monaco-editor,but so many types different，so I can not use it!

**Comment by srares13** [comment]
This library makes heavy use of the vscode module provided by the VS Code runtime. Other editors were not specifically targeted. Correct me if Im wrong, but I know that Monaco Editor does not provide the vscode module, hence you shouldn't be able to use it there.

This library has in its title "vscode", but maybe I should specify once more in the description as well that officially it is intended to work within VS Code extension development environment. So, Im sorry for the inconvinience.

**Comment by srares13** [comment]
If theres nothing more to it, Im gonna close this issue, but if there are other matters to be answered, feel free to ask.
